language: node_js
node_js:
  - "12"
  - "10"
  - "8"
env:
  - MONGOOSE_VERSION=5
  - MONGOOSE_VERSION=4
cache: yarn
git:
  depth: 3
before_script:
  - sleep 15
install:
  - yarn
  - yarn add --dev mongoose@^$MONGOOSE_VERSION
script:
  - yarn hint
  - yarn test
jobs:
  include:
  - stage: test integration
    if: false
    services: mongodb
    script:
      - yarn test-integration
  - stage: deploy
    if: env(MONGOOSE_VERSION) = 5
    node_js: "12"
    script:
      - yarn test-and-cover
      - yarn coveralls
